/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

rootProject.name = "test-partiql-version-migration"
include("v0.1-to-v0.2-migration:examples")
include("v0.1-to-v0.2-migration:migrated-examples")
include("v0.2-to-v0.3-migration:examples")
include("v0.2-to-v0.3-migration:migrated-examples")
include("v0.3-to-v0.4-migration:examples")
include("v0.3-to-v0.4-migration:migrated-examples")
include("v0.4-to-v0.5-migration:examples")
include("v0.4-to-v0.5-migration:migrated-examples")
include("v0.5-to-v0.6-migration:examples")
include("v0.5-to-v0.6-migration:migrated-examples")
include("v0.6-to-v0.7-migration:examples")
include("v0.6-to-v0.7-migration:migrated-examples")
